# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d9a5b2fa2f7604be889bbd9d7c11d8913abcc2ce32c330f96cd438ff47046a58f593d248909dbdad1688cb9df5474ee82884bd6a64fac2deda2f35be5e64dbd

test:
  secret_key_base: 32dc556ecef8599a25a9167ca8686735e987c0fa90e3cbcf63249db9292ae606e9853b42a0f7c53f03a08a73dc34e0fdb83133a862bbc6ed5c435613d410f33c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
